# https://www.dartlang.org/guides/language/analysis-options
analyzer:
  strong-mode:
    implicit-casts: false

# http://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
  - always_declare_return_types
  - annotate_overrides
  - avoid_empty_else
  - avoid_init_to_null
  - avoid_relative_lib_imports
  - avoid_return_types_on_setters
  - avoid_shadowing_type_parameters
  - avoid_types_as_parameter_names
  - await_only_futures
  - camel_case_types
  - cancel_subscriptions
  - close_sinks
  - comment_references
  - constant_identifier_names
  - control_flow_in_finally
  - curly_braces_in_flow_control_structures
  - directives_ordering
  - empty_catches
  - empty_constructor_bodies
  - empty_statements
  - hash_and_equals
  - implementation_imports
  - invariant_booleans
  - iterable_contains_unrelated_type
  - library_names
  - library_prefixes
  - list_remove_unrelated_type
  - literal_only_boolean_expressions
  - no_duplicate_case_values
  - non_constant_identifier_names
  - null_closures
  - one_member_abstracts
  - only_throw_errors
  - overridden_fields
  - package_names
  - package_prefixed_library_names
  - prefer_contains
  - prefer_equal_for_default_values
  - prefer_final_fields
  - prefer_final_locals
  - prefer_generic_function_type_aliases
  - prefer_is_empty
  - prefer_is_not_empty
  - prefer_iterable_whereType
  - prefer_single_quotes
  - prefer_typing_uninitialized_variables
  - recursive_getters
  - slash_for_doc_comments
  - test_types_in_equals
  - throw_in_finally
  - type_init_formals
  #- unawaited_futures
  - unnecessary_brace_in_string_interps
  - unnecessary_const
  - unnecessary_getters_setters
  - unnecessary_new
  - unnecessary_null_in_if_null_operators
  - unrelated_type_equality_checks
  - use_rethrow_when_possible
  - valid_regexps
