name: pub_dartlang_org
version: 0.1.0
author: Dart Team
description: The pub.dartlang.org website.
dependencies:
  appengine: '>=0.3.0 <0.4.0'
  gcloud: '>=0.1.4+1 <0.2.0'
  googleapis: '>=0.5.4 <0.6.0'
  googleapis_auth: '>=0.2.2 <0.2.3'
  http: '>=0.11.0 <0.12.0'
  intl: '>=0.11.0 <0.12.0'
  logging: '>=0.9.3 <1.0.0'
  markdown: '>=0.7.0 <0.8.0'
  mustache: '>=0.2.3 <0.3.0'
  pub_server: ">=0.1.0 <0.2.0"
  shelf: '>=0.5.6 <0.6.0'
  uuid: ">=0.5.0 <0.5.1"

dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
