name: pub_dartlang_org
version: 0.1.0
author: Dart Team
description: The pub.dartlang.org website.
dependencies:
  appengine: '>=0.2.4 <0.3.0'
  gcloud: '>=0.1.3 <0.2.0'
  markdown: '>=0.7.0 <0.8.0'
  mustache: '>=0.1.8 <0.2.0'
  shelf: '>=0.5.6 <0.6.0'
  intl: '>=0.11.0 <0.12.0'

dev_dependencies:
  unittest: any

dependency_overrides:
  pubserver:
    path: ../pkg/pubserver
  appengine:
    path: ../pkg/appengine
  gcloud:
    path: ../pkg/gcloud
  mustache:
    path: ../pkg/mustache
