name: pub_dartlang_org
version: 0.1.0
author: Dart Team
description: The pub.dartlang.org website.
sdk: ">=1.9.0 <2.0.0"
dependencies:
  appengine: '>=0.3.0 <0.4.0'
  gcloud: '>=0.3.0 <0.4.0'
  googleapis: '>=0.31.0 <0.32.0'
  googleapis_auth: '>=0.2.2 <0.2.3'
  html: '>=0.12.0 <0.13.0'
  http: '>=0.11.0 <0.12.0'
  intl: '>=0.13.0 <0.14.0'
  logging: '>=0.9.3 <1.0.0'
  markdown: '>=0.11.0 <0.12.0'
  mustache: '>=0.2.3 <0.3.0'
  pub_semver: ">=1.2.2 <2.0.0"
  pub_server: ">=0.1.0 <0.2.0"
  shelf: '>=0.5.6 <0.6.0'
  uuid: ">=0.5.0 <0.5.1"

dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
